# Generated by Django 4.0.5 on 2022-06-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_group_student_birthday_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='amountStudents',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of students'),
        ),
    ]
